
//Login
export const REQUEST_DATA1= 'REQUEST_DATA1';
export const REQUEST_ERROR1= 'REQUEST_ERROR1';
export const REQUEST_SUCCESS1= 'REQUEST_SUCCESS1';


export const REQUEST_DATA2= 'REQUEST_DATA2';
export const REQUEST_ERROR2= 'REQUEST_ERROR2';
export const REQUEST_SUCCESS2= 'REQUEST_SUCCESS2';


export const REQUEST_DATA3= 'REQUEST_DATA3';
export const REQUEST_ERROR3= 'REQUEST_ERROR3';
export const REQUEST_SUCCESS3= 'REQUEST_SUCCESS3';








